site_name: L&T的个人博物馆
site_description: 一个记录学习与生活的小站

theme:
  name: material
  custom_dir: theme
  language: zh
  palette:
    # 浅色模式
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    # 深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式

nav:
  - 主页: index.md
  - 故事:
      - 故事列表: story/index.md
      - 老公说，我宁愿死，也不想让她看见我现在的样子！: story/老公说，我宁愿死，也不想让她看见我现在的样子！.md
      - 嫁给林昭的第七年，看九三阅兵，我和孩子们哭的像傻子！: story/嫁给林昭的第七年，看九三阅兵，我和孩子们哭的像傻子！.md
      - 男友瞒着我去相亲，是县长介绍的，然后我给女儿取名叫“慢慢”！: story/男友瞒着我去相亲，是县长介绍的，然后我给女儿取名叫“慢慢”！.md
  - 课程: course/index.md
  - 友链: friends/index.md
  - 关于: about/index.md
