site_name: L&T的个人博物馆
site_description: 一个记录学习与生活的小站

theme:
  name: material
  custom_dir: theme
  language: zh
  palette:
    # 浅色模式
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    # 深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式

nav:
  - 主页: index.md
  - 课程: course/index.md
  - 随笔: 
    - 随笔首页: essay/index.md
    - 行者无疆: essay/travel/index.md
    - 光影留痕: essay/film/index.md
    - 笔墨生香: essay/book/index.md
    - 社会百态: essay/society/index.md
    - 生活点滴: essay/life/index.md
  - 友链: friends/index.md
  - 关于: about/index.md